spring.datasource.url=jdbc:mysql://localhost:3306/teach_stud_management
spring.datasource.username=root
spring.datasource.password=8177986927
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
